eve:
  url: https://esi.evetech.net

spring:
  graphql:
    graphiql:
      introspection: true
      enabled: true
    cors:
      allowed-origins: '*'
  data:
    cassandra:
#      url: 192.168.68.53
      url: localhost
      port: 9042
      keyspace-name: Orders
      username: cassandra
      password: cassandra
      data-center: datacenter1
    mongodb:
      url: mongodb://localhost
      port: 27017




management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
server:
  port: 8060
  compression:
    enabled: true
    mime-types: application/json,application/graphql+json,application/graphql,application/graphql-response+json
    min-response-size: 256


