eve:
  url: https://esi.evetech.net

spring:
  graphql:
    graphiql:
      introspection: true
      enabled: true
    cors:
      allowed-origins: '*'
  data:
    cassandra:
      name: localhost
      port: 9042
      keyspace-name: Orders
      username: cassandra
      password: cassandra


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
server:
  port: 8060


